### ISSUE TITLE
Deployment to K8s fails on Release pipeline in "./aml_service/51-deployOnAks.py"

### ISSUE THREAD

**Issue by robcamer** [praneetmsft/DevOpsForAI#1]
When running "51. Deploy on AKS" on the Release pipeline to "Prod", the script fails with this log:

2019-05-24T12:40:01.0784520Z **No AKS found in aks_webservice.json. Creating new Aks:** aks052412 and AKS Webservice: akswebservice052412
2019-05-24T12:56:09.4504573Z Creating..................................................................................................................................................................................
2019-05-24T12:56:09.9555604Z **FailedProvisioning operation finished, operation "Failed"**
2019-05-24T12:56:09.9564220Z Traceback (most recent call last):
2019-05-24T12:56:09.9565280Z   File "./aml_service/51-deployOnAks.py", line 64, in <module>
2019-05-24T12:56:09.9565687Z     **with open("aml_config/aks_webservice.json") as f:
2019-05-24T12:56:09.9566434Z FileNotFoundError: [Errno 2] No such file or directory:** 'aml_config/aks_webservice.json'
2019-05-24T12:56:09.9567086Z 
2019-05-24T12:56:09.9567287Z During handling of the above exception, another exception occurred:
2019-05-24T12:56:09.9567481Z 
2019-05-24T12:56:09.9567667Z Traceback (most recent call last):
2019-05-24T12:56:09.9568064Z   File "./aml_service/51-deployOnAks.py", line 93, in <module>
2019-05-24T12:56:09.9568339Z     aks_target.wait_for_completion(show_output=True)
2019-05-24T12:56:09.9569125Z   File "/opt/hostedtoolcache/Python/3.6.8/x64/lib/python3.6/site-packages/azureml/core/compute/compute.py", line 400, in wait_for_completion
2019-05-24T12:56:09.9569426Z     raise e
2019-05-24T12:56:09.9569914Z   File "/opt/hostedtoolcache/Python/3.6.8/x64/lib/python3.6/site-packages/azureml/core/compute/compute.py", line 393, in wait_for_completion
2019-05-24T12:56:09.9570369Z     '{}'.format(self.provisioning_state, error_response))
2019-05-24T12:56:09.9570924Z azureml.exceptions._azureml_exception.ComputeTargetException: Compute object provisioning polling reached non-successful terminal state, current provisioning state: Failed
2019-05-24T12:56:09.9571580Z Provisioning operation error:
2019-05-24T12:56:09.9571809Z StatusCode: 400
2019-05-24T12:56:09.9572189Z Message: The request is invalid
2019-05-24T12:56:10.0445164Z ##[error]Script failed with error: Error: /bin/bash failed with return code: 1
2019-05-24T12:56:10.0457760Z [command]/opt/hostedtoolcache/Python/3.6.8/x64/bin/az account clear

**Comment by papagala** [comment]
Same here!

**Comment by b4usooraj** [comment]
Any update on this error
